graphql:
  servlet:
    mapping: /app/graphql
    enabled:  true
    corsEnabled: true

logging:
  level:
    org.springframework: INFO

server:
  port: ${PORT:5000}

---

spring:
  datasource:
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    url: 'jdbc:h2:file:~/test-h2-db'
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---
spring:
  profiles: production
  datasource:
      platform: h2
      type: com.zaxxer.hikari.HikariDataSource
      url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
      driverClassName: org.postgresql.Driver
  hikari:
    connection-timeout: 30000
    maximum-pool-size: 10
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

authentication:
  jwt:
    secret: ${JWT_APP_SECRET:secretDefaultDev3346G}
